modLoader="javafml"
#clientSideOnly=true

license="${mod_license}"
loaderVersion="${loader_version_range}"

[[mods]]
    modId="${mod_id}"
    #logoFile="icon.png"
    version="${mod_version}"
    authors="${mod_authors}"
    displayName="${mod_name}" 
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"